services:
  - type: web
    name: grid-game-backend
    env: node
    plan: free
    buildCommand: npx pnpm install && npx pnpm build
    startCommand: npx pnpm start
    envVars:
      - key: NODE_ENV
        value: production
