services:
  - type: web
    name: grid-game-backend
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
