name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: haqms
          POSTGRES_USER: sobit902266
          POSTGRES_PASSWORD: sobit1033
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install PNPM
      uses: pnpm/action-setup@v3
      with:
        version: 8

    # 1. CI for grid-server
    - name: Install grid-server Dependencies
      run: pnpm install --no-frozen-lockfile
      working-directory: grid-server

    - name: Generate Prisma Client
      run: pnpm prisma generate
      working-directory: grid-server
      env:
        DATABASE_URL: "postgresql://sobit902266:sobit1033@localhost:5432/haqms"

    - name: Push Prisma Schema
      run: npx prisma db push
      working-directory: grid-server
      env:
        DATABASE_URL: "postgresql://sobit902266:sobit1033@localhost:5432/haqms"

    - name: Build grid-server
      run: pnpm build
      working-directory: grid-server
      env:
        DATABASE_URL: "postgresql://sobit902266:sobit1033@localhost:5432/haqms"

    - name: Run grid-server Tests
      run: pnpm test
      working-directory: grid-server
      env:
        DATABASE_URL: "postgresql://sobit902266:sobit1033@localhost:5432/haqms"

    # 2. CI for grid-web
    - name: Install grid-web Dependencies
      run: pnpm install --no-frozen-lockfile
      working-directory: grid-web

    - name: Build grid-web
      run: pnpm build
      working-directory: grid-web
